name: Generate Artifacts
on:
  workflow_dispatch:

env:
  YAAK_PLUGINS_DIR: checkout/plugins

jobs:
  build-artifacts:
    permissions:
      contents: write

    name: Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-24.04-arm'
            args: ''
            yaak_arch: 'arm64'
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 40
    steps:
      - name: Checkout yaakapp/app
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: install dependencies (ubuntu only)
        if: ${{ startsWith(matrix.platform, 'ubuntu') }} # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        run: cargo install --force trusted-signing-cli

      - name: Install NPM Dependencies
        run: |
          npm ci
          npm install @yaakapp/cli

      - name: Install Protoc for plugin-runtime
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run JS build
        run: npm run build

      - name: Run lint
        run: npm run lint

      - name: Checkout Yaak Plugins
        uses: actions/checkout@v4
        with:
          repository: mountain-loop/yaak-plugins
          path: ${{ env.YAAK_PLUGINS_DIR }}

      - uses: tauri-apps/tauri-action@v0
        env:
          YAAK_PLUGINS_DIR: ${{ env.YAAK_PLUGINS_DIR }}
          YAAK_TARGET_ARCH: ${{ matrix.yaak_arch }}
        with:
          args: ${{ matrix.args }}
